### ISSUE TITLE
Check sposors' logos sizes

### ISSUE THREAD

**Issue by annalisaantonioli** [esl/code-beam-europe#6]

**Comment by annalisaantonioli** [comment]
@kamila-codesync   I made a small fix, but in general, even though the images now have a fixed width and height, they can still look different from each other due to their original aspect ratios. Currently, the size is set to 170x100px, but if you want the logos to be more consistent in size, you'll need to upload edited versions. Ideally, they should be placed on a 170x100px canvas, adjusting the size of the logo accordingly.

**Comment by kamila-codesync** [comment]
Than you, I will start to replace them like that.
